site_name: Arjuna K.
site_url: https://arjkesh.github.io/
theme:
  name: material
  palette:
    - scheme: default               # Light mode
      primary: teal                 # or "lightblue"
      accent: teal                  # or "lightblue"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate                 # Dark mode
      primary: teal                 # or "lightblue"
      accent: teal                  # or "lightblue"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - About Me: index.md
  # - Projects:
  #   - ICUAlert: projects/icu_alert.md
  #   - Deep Learning Containers: projects/dlc.md
  # - Music:
  #   - Tunes: music/tunes.md

